on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        plan:
        - ghc: '8.10.7'
          resolver: 'lts-18.23'
        flags:
        - "--pedantic --ghc-options=-O2"
    runs-on: ${{ matrix.os }}
    env:
      STACK: stack --no-terminal --system-ghc --resolver ${{ matrix.plan.resolver }}
      FLAGS: ${{ matrix.flags }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.plan.ghc.plan }}
        enable-stack: true
        stack-version: latest
    - uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}-${{ matrix.plan.resolver }}
    - name: Install dependencies
      run: $STACK test --bench --only-dependencies $FLAGS
    - name: Build
      run: |
        $STACK build --bench --haddock --no-haddock-deps $FLAGS
        $STACK exec site clean
        $STACK exec site build
    - name: Test
      run: $STACK -j 1 test --bench --no-run-benchmarks --haddock --no-haddock-deps $FLAGS
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.sha }}-public
        path: public

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    steps:
    - name: Download a public
      uses: actions/download-artifact@v2
      with:
        name: ${{ github.sha }}-public
        path: public
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public



