on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        plan:
          - node-version: "16.16.0"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.plan.node-version }}
          cache: "yarn"
          cache-dependency-path: ./yarn.lock
      - name: Install dependencies
        run: yarn
      - name: Lint & Type check
        run: yarn lint && yarn type-check
      - name: Build
        run: yarn build && yarn export
      - name: add nojekyll
        run: touch ./out/.nojekyll
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}-out
          path: out
